Revert "update moodle to version 3.10"

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,75 +2,79 @@
 # process (which uses our internal CI system) this file is here for the benefit
 # of community developers git clones - see MDL-51458.
 
+sudo: required
+
+# We currently disable Travis notifications entirely until https://github.com/travis-ci/travis-ci/issues/4976
+# is fixed.
 notifications:
-  email:
-    if: env(MOODLE_EMAIL) != no
+  email: false
 
 language: php
 
-os: linux
-
-dist: bionic
-
-services:
-    - mysql
-    - docker
+php:
+    # We only run the highest and lowest supported versions to reduce the load on travis-ci.org.
+    - 7.1
+    - 5.6
 
 addons:
   postgresql: "9.6"
+  packages:
+    - mysql-server-5.6
+    - mysql-client-core-5.6
+    - mysql-client-5.6
 
-branches:
-  except:
-    - master
-    - /MOODLE_[0-9]+_STABLE/
-    - /^v[0-9]+\.[0-9]+\.[0-9]+.*/
+services:
+    - redis-server
 
-jobs:
+env:
+    # Although we want to run these jobs and see failures as quickly as possible, we also want to get the slowest job to
+    # start first so that the total run time is not too high.
+    #
+    # We only run MySQL on PHP 7.1, so run that first.
+    # CI Tests should be second-highest in priority as these only take <= 60 seconds to run under normal circumstances.
+    # Postgres is significantly is pretty reasonable in its run-time.
+
+    # Run unit tests on MySQL
+    - DB=mysqli   TASK=PHPUNIT
+
+    # Run CI Tests without running PHPUnit.
+    - DB=none     TASK=CITEST
+
+    # Run unit tests on Postgres
+    - DB=pgsql    TASK=PHPUNIT
+
+    # Perform an upgrade test too.
+    - DB=pgsql    TASK=UPGRADE
+
+matrix:
     # Enable fast finish.
     # This will fail the build if a single job fails (except those in allow_failures).
     # It will not stop the jobs from running.
     fast_finish: true
 
     include:
-        # First all the lowest php ones (7.2)
-        - php: 7.2
-          env: DB=none     TASK=CITEST
-        - php: 7.2
-          env: DB=none     TASK=GRUNT    NVM_VERSION='lts/carbon'
+          # Run grunt/npm install on lowest supported npm version
+        - php: 7.1
+          env: DB=none     TASK=GRUNT   NVM_VERSION='4'
+          # Run grunt/npm install on highest version ('node' is an alias for the latest node.js version.)
+        - php: 7.1
+          env: DB=none     TASK=GRUNT   NVM_VERSION='node'
 
-        - if: env(MOODLE_DATABASE) = "pgsql" OR env(MOODLE_DATABASE) = "all" OR env(MOODLE_DATABASE) IS NOT present
-          php: 7.2
-          env: DB=pgsql    TASK=PHPUNIT
+    exclude:
+        # MySQL - it's just too slow.
+        # Exclude it on all versions except for 7.1
 
-        - if: env(MOODLE_DATABASE) = "mysqli" OR env(MOODLE_DATABASE) = "all"
-          php: 7.2
-          env: DB=mysqli   TASK=PHPUNIT
+        - env: DB=mysqli   TASK=PHPUNIT
+          php: 5.6
 
-        # Then, conditionally, all the highest php ones (7.4)
-        - if: env(MOODLE_PHP) = "all"
-          php: 7.4
-          env: DB=none     TASK=CITEST
-        - if: env(MOODLE_PHP) = "all"
-          php: 7.4
-          env: DB=none     TASK=GRUNT    NVM_VERSION='lts/carbon'
-
-        - if: env(MOODLE_PHP) = "all" AND (env(MOODLE_DATABASE) = "pgsql" OR env(MOODLE_DATABASE) = "all" OR env(MOODLE_DATABASE) IS NOT present)
-          php: 7.4
-          env: DB=pgsql    TASK=PHPUNIT
-
-        - if: env(MOODLE_PHP) = "all" AND (env(MOODLE_DATABASE) = "mysqli" OR env(MOODLE_DATABASE) = "all")
-          php: 7.4
-          env: DB=mysqli   TASK=PHPUNIT
+        # Moodle 2.7 is not compatible with PHP 7 for the upgrade test.
+        - env: DB=pgsql    TASK=UPGRADE
+          php: 7.1
 
 cache:
     directories:
       - $HOME/.composer/cache
       - $HOME/.npm
-
-before_install:
-    - docker run -d -p 127.0.0.1:8080:80 --name exttests moodlehq/moodle-exttests
-    # Avoid IPv6 default binding as service (causes redis not to start).
-    - sudo service redis-server start --bind 127.0.0.1
 
 install:
     - >
@@ -78,10 +82,10 @@ install:
         then
             sudo mkdir /mnt/ramdisk
             sudo mount -t tmpfs -o size=1024m tmpfs /mnt/ramdisk
-            sudo service mysql stop
+            sudo stop mysql
             sudo mv /var/lib/mysql /mnt/ramdisk
             sudo ln -s /mnt/ramdisk/mysql /var/lib/mysql
-            sudo service mysql restart
+            sudo start mysql
         fi
     - >
         if [ "$DB" = 'pgsql' ];
@@ -101,6 +105,7 @@ install:
                 echo 'auth.json' >> .git/info/exclude
             fi
 
+            # Enable Redis.
             echo 'extension="redis.so"' > /tmp/redis.ini
             phpenv config-add /tmp/redis.ini
 
@@ -120,7 +125,7 @@ install:
 before_script:
     - phpenv config-rm xdebug.ini
     - >
-      if [ "$TASK" = 'PHPUNIT' ];
+      if [ "$TASK" = 'PHPUNIT' -o "$TASK" = 'UPGRADE' ];
       then
         # Copy generic configuration in place.
         cp config-dist.php config.php ;
@@ -176,21 +181,7 @@ before_script:
         sed -i \
           -e "/require_once/i \\\$CFG->phpunit_dataroot = '\/home\/travis\/roots\/phpunit';" \
           -e "/require_once/i \\\$CFG->phpunit_prefix = 'p_';" \
-          config.php ;
-        # Enable test external resources
-        sed -i \
-          -e "/require_once/i \\define('TEST_EXTERNAL_FILES_HTTP_URL', 'http://127.0.0.1:8080');" \
-          -e "/require_once/i \\define('TEST_EXTERNAL_FILES_HTTPS_URL', 'http://127.0.0.1:8080');" \
-          config.php ;
-
-        # Redis cache store tests
-        sed -i \
-          -e "/require_once/i \\define('TEST_CACHESTORE_REDIS_TESTSERVERS', '127.0.0.1');" \
-          config.php ;
-        # Redis session tests, but not for PHP 7.2 and up. See MDL-60978 for more info.
-        redissession="define('TEST_SESSION_REDIS_HOST', '127.0.0.1');"
-        sed -i \
-          -e "/require_once/i \\${redissession}" \
+          -e "/require_once/i \\define('TEST_SESSION_REDIS_HOST', '127.0.0.1');" \
           config.php ;
 
         # Initialise PHPUnit for Moodle.
@@ -220,7 +211,7 @@ before_script:
         # We need the official upstream for comparison
         git remote add upstream https://github.com/moodle/moodle.git;
 
-        git fetch upstream MOODLE_310_STABLE;
+        git fetch upstream MOODLE_33_STABLE;
         export GIT_PREVIOUS_COMMIT="`git merge-base FETCH_HEAD $TRAVIS_COMMIT`";
         export GIT_COMMIT="$TRAVIS_COMMIT";
         export UPSTREAM_FETCH_HEAD=`git rev-parse FETCH_HEAD`
@@ -231,11 +222,37 @@ before_script:
         export phpcmd=`which php`;
       fi
 
+    ########################################################################
+    # Upgrade test
+    ########################################################################
+    - >
+      if [ "$TASK" = 'UPGRADE' ];
+      then
+        # We need the official upstream.
+        git remote add upstream https://github.com/moodle/moodle.git;
+
+        # Checkout 27 STABLE branch.
+        git fetch upstream MOODLE_27_STABLE;
+        git checkout MOODLE_27_STABLE;
+
+        # Perform the upgrade
+        php admin/cli/install_database.php --agree-license --adminpass=Password --adminemail=admin@example.com --fullname="Upgrade test" --shortname=Upgrade;
+
+        # Return to the previous commit
+        git checkout -;
+
+        # Perform the upgrade
+        php admin/cli/upgrade.php --non-interactive --allow-unstable ;
+
+        # The local_ci repository can be used to check upgrade savepoints.
+        git clone https://github.com/moodlehq/moodle-local_ci.git local/ci ;
+      fi
+
 script:
     - >
       if [ "$TASK" = 'PHPUNIT' ];
       then
-        vendor/bin/phpunit --fail-on-risky --disallow-test-output --verbose;
+        vendor/bin/phpunit;
       fi
 
     - >
@@ -250,16 +267,23 @@ script:
         grunt ;
         # Add all files to the git index and then run diff --cached to see all changes.
         # This ensures that we get the status of all files, including new files.
-        # We ignore npm-shrinkwrap.json to make the tasks immune to npm changes.
         git add . ;
-        git reset -- npm-shrinkwrap.json ;
         git diff --cached --exit-code ;
       fi
 
-after_script:
+    ########################################################################
+    # Upgrade test
+    ########################################################################
     - >
-      if [ "$TASK" = 'PHPUNIT' ];
+      if [ "$TASK" = 'UPGRADE' ];
       then
-        EXTTESTS_HITS=$(docker logs exttests 2>&1 | grep -Fv -e 'AH00558' -e '[pid 1]' | wc -l)
-        echo -e "\nTest local resources number of hits: ${EXTTESTS_HITS}.\n"
+        cp local/ci/check_upgrade_savepoints/check_upgrade_savepoints.php ./check_upgrade_savepoints.php
+        result=`php check_upgrade_savepoints.php`;
+        # Check if there are problems
+        count=`echo "$result" | grep -P "ERROR|WARN" | wc -l` ;
+        if (($count > 0));
+        then
+          echo "$result"
+          exit 1 ;
+        fi
       fi
